A:
  - ABELE
  - ABRAMI
  - ACHILLE
  - ADALBERTO
  - ADAMO
  - ADOLFO
  - ADRIANO
  - AGOSTINO
  - ALBANO
  - ALBERICO
  - ALBERTO
  - ALESSANDRO
  - ALESSIO
  - ALFREDO
  - ALONZO
  - ALFONSO
  - ALVISE
  - AMADEO
  - AMATO
  - AMERIGO
  - ANDREA
  - ANGELO
  - ANTONELLO 
  - ANTONINO
  - ARMANDO
  - ARNALDO
  - ARRIGO
  - ARTURO

B:
  - BARTOLOMEO
  - BASILIO
  - BENEDETTO
  - BENIAMINO
  - BEPPE
  - BERNARDO
  - BERTO
  - BERTRANDO
  - BIAGINO
  - BONIFACIO 
  - BRUNO

C: &C
  - CAMILLO
  - CARLO
  - CARMINE
  - CESARE
  - CIRILLO
  - CLAUDIO
  - CORNELIO
  - COSIMO
  - COSTANTINO 
  - COSTANZO
  - CRISTIANO
  - CRISTOFORO

D:
  - DAMIANO
  - DANILO
  - DANTE
  - DARIO
  - DAVIDE
  - DEMETRIO
  - DESIDERIO
  - DINO
  - DOMENICO
  - DONATELLO
  - DORIANO

E:
  - EDMONDO
  - EDOARDO
  - EDVIGE
  - ELIO
  - EMANUELE
  - EMILIO
  - ENNIO
  - ENRICO
  - ENZO
  - ERASMO
  - ERCOLE
  - ERNESTO
  - ETTORE
  - EUGENIO
  - EUSTACHIO
  - EVARISTO
  - EZIO

F:
  - FABIO
  - FABRIZIO 
  - FAUSTO
  - FEDELE
  - FEDERIGO
  - FELICIANO
  - FERDINANDO
  - FERRUCCIO
  - FILIBERTO
  - FILIPPO
  - FIORENZO
  - FIORINO
  - FIRMINO
  - FLAVIO
  - FLORIANO
  - FORTUNATO
  - FRANCESCO
  - FRANCO
  - FREDO
  - FULGENZIO
  - FULVIO

G: &G
  - GABRIELE
  - GAETANO
  - GASPARE
  - GAVINO
  - GENNARO
  - GERARDO
  - GERONIMO
  - GERVASIO
  - GIACOBBE
  - GIACOMO
  - GIANNI
  - GILBERTO
  - GINO
  - GIOACCHINO
  - GIORDANO
  - GIORGIO
  - GIOSUÈ
  - GIOVANNI
  - GIRALDO
  - GIULIANO
  - GIUSEPPE
  - GIUSTINO
  - GLAUCO
  - GOFFREDO
  - GREGORIO
  - GUALTIERO
  - GUGLIELMO
  - GUIDO
  - GUSTAVO

H:
  - HADRIAN
  - HORATIO

I: &I
  - IGNAZIO
  - ISIDORO

J:
  - GERARDO
  - GERONIMO
  - GERVASIO
  - GIACOBBE
  - GIACOMO
  - GIANNI
  - GINO
  - GIOACCHINO
  - GIORDANO
  - GIORGIO
  - GIOSUÈ
  - GIOVANNI
  - GIRALDO
  - GIULIANO
  - GIUSEPPE
  - GIUSTINO

K: *C

L:
  - LAMBERTO
  - LAZZARO
  - LEONARDO
  - LIBERATORE
  - LIBORIO
  - LORENZO
  - LUCA
  - LUCIANO
  - LUDOVICO
  - LUIGI

M:
  - MANFREDO
  - MARCELLO
  - MARCO
  - MARIANO
  - MARINO
  - MARIO
  - MARTINO
  - MARZIO
  - MASSIMILIANO
  - MASSIMO
  - MATTIA
  - MATTEO
  - MAURIZIO
  - MAURO
  - MICHELANGELO
  - MICHELE
  - MODESTO

N:
  - NALDO
  - NARCISO
  - NERO
  - NESTORE
  - NEVIO
  - NICCOLÒ
  - NINO

O:
  - ODDO
  - ORLANDO
  - ORSINO
  - OSVALDO

P:
  - PAOLO
  - PASQUALE
  - PATRIZIO
  - PELLEGRINO
  - PIERO PETER
  - PINO
  - PLINIO 
  - POMPEO
  - PONZIO
  - PRIMO
  - PROSPERO
  - PRUDENZIO

Q: QUIRINO

R:
  - RAFFAELLO
  - RAIMONDO
  - REMIGIO
  - RENATO
  - RICCARDO
  - ROBERTO
  - ROCCO
  - RODOLFO
  - RODRIGO
  - ROLANDO
  - ROMOLO
  - RUFINO
  - RUGGIERO

S: &S
  - SALVATORE
  - SAMUELE
  - SANSONE
  - SANTINO
  - SANTO
  - SATURNINO
  - SAVERIO
  - SEBASTIANO
  - SERAFINO
  - SERGIO
  - SILVESTRO
  - STEFANO

T:
  - TADDEO
  - TAMMARO
  - TEOBALDO
  - TEODORO
  - TEOFILO
  - TIMOTEO
  - TITO
  - TOMMASO

U:
  - UBERTO
  - UGO HUGH
  - ULDERICO
  - ULISSE
  - UMBERTO
  - URBANO

V:
  - VALENTINO
  - VESPASIANO
  - VILFREDO
  - VINCENZO
  - VINICIO
  - VIRGILIO
  - VITALE
  - VITO
  - VITTORE

W: *G

X: *S

Y: *I

Z: *S
