A:
  - ADRIANA
  - AGNESE
  - AGOSTINA
  - ALBERTA
  - ALESSANDRA
  - ALESSIA
  - AMALIA
  - ANDREA
  - ANGELICA
  - ANNABELLA
  - ANTONELLA
  - ANTONIA

B:
  - BATTISTA
  - BENEDETTA
  - BERNARDETTA
  - BERTA
  - BIANCA
  - BIBIANA
  - BONAVENTURA
  - BRIGIDA
  - BRUNA

C: &C
  - CAMILLA
  - CARLA
  - CARLOTTA
  - CARMINA
  - CAROLA
  - CASSANDRA
  - CATERINA
  - CECILIA
  - CHIARA
  - CINZIA
  - CLAUDIA
  - CLEMENTINA
  - COLOMBA
  - CONCETTA
  - CORNELIA
  - COSIMA
  - CRISTINA

D:
  - DAMIANA
  - DANIELA
  - DARIA
  - DEBORA
  - DELFINA
  - DELIA
  - DESIDERIA
  - DOMENICA
  - DONATELLA   
  - DOROTEA

E:
  - EDMONDA
  - ELENA
  - ELEONORA
  - ELETTRA
  - ELIANA
  - ELISABETTA
  - ELOISA
  - ELVIRA
  - EMANUELA
  - EMILIA
  - ENRICA
  - ERMELINDA
  - ERNESTA
  - EUGENIA
  - EVELINA

F:
  - FABIA
  - FABIANA
  - FABIOLA
  - FABRIZIA 
  - FAUSTINA 
  - FEDERICA
  - FELICIANA 
  - FERNANDA
  - FIAMMETTA
  - FILIPPA
  - FILOMENA
  - FIORELLA
  - FIORENZA 
  - FLAVIA
  - FLORIANA
  - FORTUNATA
  - FRANCESCA

G:
  - GABRIELLA
  - GAETANA
  - GAIA
  - GENOVEFFA
  - GESSICA
  - GIA
  - GIADA
  - GINEVRA
  - GIONATA
  - GIORGIA
  - GIOSETTA
  - GIOVANNA
  - GISELLA
  - GIUDITTA
  - GIULIA
  - GIULIANA
  - GIULIETTA
  - GIUSEPPA
  - GIUSTINA

H: 
  - HADRIA
  - HORATIA

I:
  - IMELDA
  - IOLANDA
  - ISABELLA
  - ISIDORA

J:
  - GENOVEFFA
  - GESSICA
  - GIA
  - GIADA
  - GINEVRA
  - GIONATA
  - GIORGIA
  - GIOSETTA
  - GIOVANNA
  - GISELLA
  - GIUDITTA
  - GIULIA
  - GIULIANA
  - GIULIETTA
  - GIUSEPPA
  - GIUSTINA

K: *C

L:
  - LAURETTA
  - LEONARDA
  - LEONORA
  - LIDIA
  - LILIANA
  - LORENZA
  - LUANA
  - LUCIA
  - LUCREZIA

M:
  - MADDALENA
  - MAFALDA
  - MANUELA
  - MARCELLA
  - MARGHERITA
  - MARIA
  - MARIANNA
  - MARINA
  - MARISA
  - MARTA
  - MARTINA
  - MARZIA
  - MAURA
  - MICHELA
  - MICHELINA
  - MILENA
  - MIRABELLA
  - MIRELLA
  - MONICA

N:
  - NADIA
  - NARCISA
  - NATALIA
  - NICOLA
  - NINA
  - NORA
  - NORMA

O:
  - OSANNA
  - OTTAVIA

P:
  - PAOLA
  - PATRIZIA
  - PERLA
  - PIERA

Q: *C

R:
  - RACHELE
  - RAFFAELLA
  - RAIMONDA
  - REGINA
  - RENATA
  - RICCARDA
  - ROBERTA
  - ROSA
  - ROSALINDA
  - ROSANNA
  - RUBINA

S: &S
  - SABINA
  - SAMANTA
  - SANTA
  - SAVERIA
  - SERAFINA
  - SILVIA
  - SIMONA
  - SOFIA
  - SONIA
  - STEFANIA
  - STELLA

T:
  - TEODORA
  - TEOFILA
  - TERESA

U:
  - URBANA

V: &V
  - VALENTINA 
  - VALERIA
  - VANESSA
  - VERONICA
  - VINCENZA
  - VIOLETTA
  - VITA
  - VITTORIA
  - VIVIANA

W: *V

X: *S

Y: IOLANDA

Z: ZITA
