A:
  - ABANDONATO
  - ABATANGELO
  - ABATANTUONO
  - ABATEGIOVANNI
  - ABATESCIANNI
  - ABBADELLI
  - ABBASCIA
  - ABBATANGELO
  - ABBATANTUONO
  - ABBATELLI
  - ABBATICCHIO
  - ABBIATI
  - ABBRACCIABENE
  - ABELLÓ
  - ACCARDI
  - ACCIAIOLI
  - ACCONCIO
  - ACCORSI
  - ACCURSIO
  - ACERBI
  - ACONI
  - ACQUAFREDDA
  - ACQUARONE
  - ACQUATI
  - ADALARDI
  - ADAMOLI
  - ADDARIO
  - ADELARDI
  - ADESSI
  - ADIMARI
  - ADRIATICO
  - AFFINI
  - AGGIO
  - AGNELLI
  - AGNELLUTTI
  - AGNUSDEI
  - AGOSTINI
  - AGRESTA
  - AGRIOLI
  - AIELLO
  - AIOLFI
  - AIRALDI
  - ALAGONA
  - ALAMANNI
  - ALBANESI
  - ALBANI
  - ALBERGHINI
  - ALBERICI
  - ALBERIGHI
  - ALBINI
  - ALBRICCI
  - ALCHERI
  - ALDEBRANDI
  - ALDERISI
  - ALDUINO
  - ALEMAGNA
  - ALESINI
  - ALESIO
  - ALESSANDRI
  - ALESSI
  - ALFERO
  - ALIBERTI
  - ALINARI
  - ALIPRANDI
  - ALLEGRI
  - ALOISI
  - ALTAMURA
  - ALTIMARI
  - ALTOVITI
  - ALUNNI
  - AMADEI
  - AMADORI
  - AMALBERTI
  - AMANTEA
  - AMATORE
  - AMBROSI
  - AMERIGHI
  - AMORETTO
  - ANGIOLI
  - ANSALDI
  - ANSELMETTI
  - ANTONELLI
  - ANTONINI
  - AQUINO
  - ARDICCIONI
  - ARDIZZONE
  - ARDOVINI
  - ARINGHERI
  - ARLOTTI
  - ARMANI
  - ARMATI
  - ARMONNI
  - ARNOLFI
  - ARNONI
  - ARRIGHETTI
  - ARRIGUCCI
  - AUCCIELLO
  - AZZARÀ

B:
  - BAGGIO
  - BAGNOLI
  - BALBONI
  - BALDINI
  - BALDINOTTI
  - BALDOVINI
  - BANDONI
  - BARBIERI
  - BARONE
  - BARSETTI
  - BARTALOTTI
  - BARTOLOMEI
  - BARZETTI
  - BASSANELLI
  - BASSANI
  - BASSO
  - BASURTO
  - BATTAGLIA
  - BAZZOLI
  - BELLANDINI
  - BELLINCIONI
  - BELLINI
  - BELLO
  - BELLONI
  - BELLUOMI
  - BELMONTE
  - BENCIVENNI
  - BENEDETTI
  - BENENATI
  - BENINI
  - BENIVIENI
  - BENVENUTI
  - BERARDI
  - BERGAMASCHI
  - BERTI
  - BERTOLINI
  - BIANCARDI
  - BIANCHI
  - BICCHIERI
  - BIONDI
  - BOERIO
  - BOLOGNA
  - BORGHI
  - BORGNINO
  - BORGOGNI
  - BOVERI
  - BRAMBANI
  - BRAMBILLA
  - BRIOSCHI
  - BRIVIO
  - BRUNETTI
  - BUFFONE
  - BULGARELLI
  - BULGARI
  - BUONARROTI
  - BUSTO

C:
  - CAIAZZO
  - CAIVANO
  - CALABRESE
  - CALLIGARIS
  - CAMPANA
  - CAMPO
  - CAPELLO
  - CAPITANI
  - CARBONI
  - CARIDEO
  - CARLEVARO
  - CARRACCI
  - CARRARA
  - CARUSO
  - CASSANO
  - CATALANO
  - CATTANEO
  - CAVALCANTE
  - CAVALLO
  - CINGOLANI
  - CIPRIANI
  - CISTERNINO
  - COLOMBERA
  - COLOMBO
  - COMO
  - CONFORTOLA
  - CORVI
  - COSTA
  - COSTANTINI
  - COSTANZO
  - CRACCHIOLO
  - CREMASCHI
  - CREMONA
  - CREMONESI
  - CROCE
  - CROCETTI
  - CUCINOTTA
  - CUOCCO

D:
  - D'AMBROSIO
  - DAMIANI
  - D'AMORE
  - D'ANGELO
  - D'ANTONIO
  - DINAPOLI
  - DONATI
  - D'ONOFRIO
  - DURANTE

E:
  - EPISCOPO
  - ERMACORA
  - ESPOSITO
  - EVANGELISTA

F:
  - FABBRI
  - FALCO
  - FARALDO
  - FARINA
  - FATTORE
  - FAUSTI
  - FAVERO
  - FERMI
  - FERRARI
  - FERRERO
  - FERRO
  - FIERRO
  - FILIPPI
  - FIORE
  - FISCELLA
  - FONDA
  - FONTANA
  - FORTUNATO
  - FRANCO
  - FRANZESE

G:
  - GABRIELLI
  - GAGLIARDI
  - GANZA
  - GARFAGNINI
  - GAROFALO
  - GASPARI
  - GATTI
  - GENOVESE
  - GERMANO
  - GIANNINO
  - GIMONDI
  - GIORDANO
  - GISMONDI
  - GIÙGOVAZ
  - GIUNTA
  - GORETTI
  - GRECO
  - GRIMALDI
  - GRONCHI
  - GUARNERI
  - GUERRIERO
  - GUIDI
  - GUTTUSO

H: &popular
   - ROSSI
   - RUSSO
   - FERRARI
   - ESPOSITO
   - BIANCHI
   - ROMANO
   - COLOMBO
   - RICCI
   - MARINO
   - DE LUCA
   - MANCINI
   - GIORDANO
   - RIZZO
   - LOMBARDI
   - MORETTI

I:
  - IDONI
  - INNOCENTI

J: *popular

K: *popular

L:
  - LABRIOLA
  - LÀCONI
  - LAGANÀ
  - LAGOMARSÌNO
  - LAGORIO
  - LAGUARDIA
  - LAMBERTI
  - LANDOLFI
  - LATERZA
  - LAURITO
  - LAZZARI
  - LECCESE
  - LEGGIÈRI
  - LÈMMI
  - LEONE
  - LOCATELLI
  - LOMBARDI
  - LUPO
  - LUZZATTO

M:
  - MAESTRI
  - MAGRO
  - MANCINI
  - MANFREDI
  - MANFREDONIA
  - MANTOVANI
  - MARCHEGIANO
  - MARCHESI
  - MARCHETTI
  - MARCHIONI
  - MARCONI
  - MARIANI
  - MARINO
  - MARTELLI
  - MARTINELLI
  - MAZZA
  - MESSANA
  - MICHELI
  - MILANI
  - MODUGNO
  - MONDADORI
  - MONTAGNA
  - MONTANARI
  - MORANDI
  - MORETTI
  - MOSCHELLA
  - MOSCONI
  - MURARO

N:
  - NAGGIA
  - NALDI
  - NANNINI
  - NAPOLEONI
  - NAPOLETANI
  - NAPOLIELLO
  - NARDI
  - NARDOVINO
  - NASATO
  - NASCIMBENE
  - NATALE
  - NAZARIO
  - NECCHI
  - NEGRINI
  - NENCI
  - NERONI
  - NERVETTI
  - NESPOLA
  - NICASTRO
  - NICCHI
  - NICODEMO
  - NICOLOSI
  - NICOSIA
  - NICOTERA
  - NIERI
  - NIZZOLA
  - NOSCHESE
  - NOTARO
  - NOTORIANO

O:
  - OBERTI
  - OBERTO
  - ONGARO
  - ORSINI

P:
  - PADOVANO
  - PAGANI
  - PALLADINO
  - PALMISANO
  - PALUMBO
  - PANZAVECCHIA
  - PARISI
  - PARODI
  - PARRINO
  - PASSERINI
  - PASTORE
  - PATERNOSTER
  - PAVESI
  - PAVONE
  - PECORA
  - PEDROTTI
  - PELLEGRINO
  - PERUGIA
  - PESARESI
  - PESARO
  - PETRI
  - PHERIGO
  - PIAZZA
  - PICCIRILLO
  - PICCOLI
  - PIERNO
  - PIOVENE
  - PIRAINO
  - PISANI
  - PITTALUGA
  - POGGIO
  - PONTECORVO
  - PORTELLI
  - PORTOGHESE
  - POTENZA
  - POZZI
  - PROFETA
  - PROSDOCIMI
  - PROVENZANO
  - PUGLIESE

Q:
  - QUARANTA
  - QUATTROCCHI

R:
  - RAGNO
  - RAIMONDI
  - RANERI
  - RAPALLINO
  - RAVENNA
  - RICCHETTI
  - RICCI
  - RINALDI
  - RIZZO
  - ROBUSTELLI
  - ROCCA
  - ROCCO
  - ROMAGNA
  - ROMAGNOLI
  - ROMANO
  - ROMERO
  - RONCALLI
  - RONCHI
  - ROSSI
  - ROSSINI
  - ROTOLO
  - ROVIGATTI
  - RUGGERI
  - RUSSO
  - RUSTICI
  - RUZZIER

S:
  - SALUCCI
  - SALVAGGI
  - SALVAI
  - SALVATICI
  - SANSONE
  - SANTINI
  - SANTORO
  - SAPIENTI
  - SARTINI
  - SAVONA
  - SCARPA
  - SCARSI
  - SCAVO
  - SCIACCA
  - SCIACCHITANO
  - SCIARRA
  - SCORDATO
  - SCOTTI
  - SCUTESE
  - SEBASTIANI
  - SEBASTINO
  - SEGRETI
  - SELMONE
  - SELVAGGIO
  - SERAFINI
  - SERPICO
  - SIENA
  - SILVESTRI
  - SINAGRA
  - SOLDATI
  - SORDI
  - SORIANO
  - SORRENTINO
  - SPANÒ
  - SPARACELLO
  - SPEZIALE
  - SULTANA

T:
  - TAFANI
  - TAMÀRO
  - TAMBOIA
  - TARANTINO
  - TAVERNA
  - TEDESCO
  - TERRANOVA
  - TERZI
  - TESSARO
  - TESTA
  - TIRABOSCHI
  - TIVOLI
  - TODARO
  - TOLONI
  - TORNINCASA
  - TOSELLI
  - TRAPANI
  - TRAVERSINI
  - TUMICELLI
  - TURATI
  - TURCHI

U:
  - UBERTI
  - UCCELLO
  - UGGERI
  - UNGARETTI
  - UNGARO

V:
  - VACCARO
  - VALENTI
  - VALENTINI
  - VALERIO
  - VARANO
  - VENETIANER
  - VENTIMIGLIA
  - VENTURA
  - VERONA
  - VERONESI
  - VESCOVI
  - VESPA
  - VESTRI
  - VICARIO
  - VILLA
  - VINCI
  - VITALI
  - VITERI
  - VOLTOLINI

W: *popular

X: *popular

Y: *popular

Z:
  - ZAMBRANO
  - ZANETTI
  - ZANGARI
  - ZAPPA
  - ZUNINO
