AGNES: AGNESE
ALEX: ALESSANDRA
ALEXANDRA: ALESSANDRA
ALEXIA: ALESSIA
ALEXIS: ALESSIA
ALLIE: ALBERTA
ALLISON: ALBERTA
ALLY: ALBERTA
ALYSSA: ALESSIA
AMANDA: AMALIA
ANDREA: ANDREA
ANGELA: ANGELICA
ANGELICA: ANGELICA
ANGIE: ANGELICA
ANA: ANNABELLA
ANNA: ANNABELLA
AUDREY: ADRIANA
BRIDGET: BRIGIDA
CAMILA: CAMILLA
CAMILLE: CAMILLA
CARLY: CARLA
CARMEN: CARMINA
CAROL: CAROLA
CAROLE: CAROLA
CAROLINE: CAROLA
CASSIE: CASSANDRA
CASSY: CASSANDRA
CATHERINE: CATERINA
CATHY: CATERINA
CHARLOTTE: CARLOTTA
CHRISTINA: CRISTINA
CHRISTY: CRISTINA
CLAIRE: CHIARA
CLARA: CHIARA
CLAUDIA: CLAUDIA
CLEMENTINE: CLEMENTINA
CYNTHIA: CINZIA
DANIELA: DANIELA
DANIELLE: DANIELA
DEB: DEBORA
DEBORAH: DEBORA
DOROTHY: DOROTEA
ELEANOR: LEONORA
ELENA: ELENA
ELIZABETH: ELISABETTA
ELLEN: ELENA
ELY: ELENA
ELOISE: ELOISA
EMILY: EMILIA
EMMA: EMILIA
EMY: EMILIA
ESTEFANIA: STEFANIA
EVELYN: EVELINA
FRANCES: FRANCESCA
FRANCESCA: FRANCESCA
GABBY: GABRIELLA
GABRIELLA: GABRIELLA
GENEVIEVE: GENOVEFFA
GEORGIA: GIORGIA
GIGI: GIGI
GISELLE: GISELLA
ISABEL: ISABELLA
ISABELLA: ISABELLA
ISABELLE: ISABELLA
JADE: GIADA
JESS: GESSICA
JESSICA: GESSICA
JESSIE: GESSICA
JUDITH: GIUDITTA
JULIA: GIULIA
JULIANA: GIULIANA
JULIETTE: GIULIETTA
JUSTINE: GIUSTINA
KATHERINE: CATERINA
KATHY: CATERINA
KRISTINA: CRISTINA
LAURA: LAURETTA
LAUREN: LEONARDA
LEA: LIA
LEAH: LIA
LILLIAN: LILIANA
LILLITH: LILIANA
LILY: LILIANA
LIZ: ELISABETTA
LIZZIE: ELISABETTA
LUANNE: LUANA
LUCY: LUCIA
LYDIA: LIDIA
MADDIE: MADDALENA
MADDY: MADDALENA
MADELINE: MADDALENA
MADISON: MADDALENA
MARCIA: MARZIA
MARIE: MARIA
MARISSA: MARISA
MARTHA: MARTA
MARY: MARIA
MARYANNE: MARIANNA
MATILDA: MAFALDA
MICHAELA: MICHELA
MICHELLE: MICHELINA
MIKAYLA: MICHELA
MONICA: MONICA
NADYA: NADIA
NAT: NATALIA
NATALIE: NATALIA
NICKY: NICOLA
NICOLE: NICOLA
NIKKI: NICOLA
NINA: NINA
PATRICIA: PATRIZIA
PATTIE: PATRIZIA
PAULA: PAOLA
PEARL: PERLA
RACHAEL: RACHELE
RACHEL: RACHELE
RENEE: RENATA
ROSA: ROSALINDA
ROSE: ROSA
ROXANNE: ROSANNA
ROXY: ROSANNA
SAMANTHA: SAMANTA
SONYA: SONIA
SOPHIA: SOFIA
SUE: SUSANNA
SUSAN: SUSANNA
STEPHANIE: STEFANIA
SYLVIA: SILVIA
THERESA: TERESA
VICKY: VITTORIA
VICTORIA: VITTORIA
VIOLET: VIOLETTA
VIVIAN: VIVIANA
YOLANDA: IOLANDA
