ABRAHAM: ABRAMI
ADAM: ADAMO
ADRIAN: ADRIANO
ALBERT: ALBERTO
ALEX: ALESSANDRO
ALEXANDER: ALESSANDRO
ALEXIS: ALESSIO
ALEXY: ALESSIO
ALFONSO: ALFONSO
ALFRED: ALFREDO
ALONZO: ALONZO
ANDREW: ANDREA
ANDY: ANDREA
ANTHONY: ANTONINO
ANTON: ANTONIO
ANTONY: ANTONINO
ARNOLD: ARNALDO
ART: ARTURO
ARTHUR: ARTURO
ARTURO: ARTURO
AUGUSTINE: AGOSTINO
BART: BARTOLOMEO
BEN: BENIAMINO
BENJAMIN: BENIAMINO
BERNARD: BERNARDO
BRIAN: BRUNO
BRUNO: BRUNO
BRYAN: BRUNO
CAMILO: CAMILLO
CARL: CARLO
CARLOS: CARLO
CARMEN: CARMINE
CESAR: CESARE
CHARLES: CARLO
CHRIS: CRISTOFORO
CHRISTIAN: CRISTIANO
CHRISTOPHER: CRISTOFORO
CRISTIAN: CRISTIANO
DANIEL: DANILO
DAVE: DAVIDE
DAVID: DAVIDE
DEMETRI: DEMETRIO
DOM: DOMENICO
DOMINIC: DOMENICO
DON: DONATELLO
ED: EDOARDO
EDDIE: EDOARDO
EDMUND: EDMONDO
EDUARDO: EDOARDO
EDWARD: EDOARDO
ERIC: ULDERICO
FELIPE: FILIPPO
FIDEL: FEDELE
FRANCISCO: FRANCESCO
FRANK: FRANCO
FRED: FREDO
FREDDY: FEDERIGO
FREDERICK: FEDERIGO
GABE: GABRIELE
GABRIEL: GABRIELE
GEORGE: GIORGIO
GERALD: GIRALDO
GERARD: GERARDO
GILBERT: GILBERTO
GREG: GREGORIO
GREGORY: GREGORIO
GUS: AGOSTINO
HARRY: ARRIGO
HECTOR: ETTORE
HENRY: ENRICO
HERMAN: ARMANDO
JACOB: GIACOBBE
JAKE: GIACOBBE
JAMES: GIACOMO
JASPER: GASPARE
JEROME: GERONIMO
JIM: GIACOMO
JOACHIM: GIOACCHINO
JOE: GIORGIO
JOHAN: GIOVANNI
JOHN: GIANNI
JOHNATHAN: GIOVANNI
JONATHAN: GIOVANNI
JORDAN: GIORDANO
JOSEPH: GIUSEPPE
JOSH: GIOSUE
JOSHUA: GIOSUE
JULIAN: GIULIANO
JUSTIN: GIUSTINO
LAURENCE: LORENZO
LAWRENCE: LORENZO
LEO: LEONARDO
LOREN: LORENZO
LOUIS: LUIGI
LUCAS: LUCIANO
LUDWIG: LUDOVICO
LUKE: LUCIANO
MARIANO: MARIANO
MARIO: MARIO
MARK: MARCO
MARTIN: MARTINO
MATT: MATTEO
MATTHAUS: MATTIA
MATTHEW: MATTEO
MATTHIAS: MATTIA
MAX: MASSIMO
MICHAEL: MICHELE
MIKE: MICHELE
MILES: CAMILLO
NICHOLAS: NICCOLÒ
NICK: NICCOLO
NICO: NICCOLO
NICOLAS: NICCOLO
OSWALD: OSVALDO
OTTO: ODDO
PAT: PATRIZIO
PATRICK: PATRIZIO
PAUL: PAOLO
PETE: PIERO
PETER: PIERO
PHIL: FILIPPO
PHILIP: FILIPPO
PHILLIP: FILIPPO
QUENTIN: QUIRINO
RAFAEL: RAFFAELLO
RAPHAEL: RAFFAELLO
RAY: RAIMONDO
RAYMOND: RAIMONDO
RICHARD: RICCARDO
RICK: RICCARDO
RICKY: RICCARDO
ROB: ROBERTO
ROBERT: ROBERTO
ROLAND: ORLANDO
SAM: SAMUELE
SAMMY: SAMUELE
SAMUEL: SAMUELE
SEBASTIAN: SEBASTIANO
STEPHEN: STEFANO
STEVE: STEFANO
STEVEN: STEFANO
TED: TEODORO
THEODORE: TEODORO
THOMAS: TOMMASO
TIM: TIMOTEO
TIMOTHY: TIMOTEO
TOM: TOMMASO
TOMAS: TOMMASO
TYLER: TITO
VINCENT: VINCENZO
VIRGIL: VIRGILIO
WALTER: GUALTIERO
WILFRED: VILFREDO
WILL: GUGLIELMO
WILLIAM: GUGLIELMO
XAVIER: SAVERIO
